<?php


namespace Modules\Inventory\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Inventory\Models\Item;

class ItemRepository extends EloquentBaseRepository
{
    public $model = Item::class;

    public function getAll($params = [], $query = null)
    {

        if (isset($params['inputs']['search'])) {
            $query = Item::where('id','like', '%'.$params['inputs']['search'].'%')
            ->orWhere('description','like', '%'.$params['inputs']['search'].'%')
            ->orWhere('unit_price','like', '%'.$params['inputs']['search'].'%');
        }

        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}
