<?php

use Illuminate\Database\Seeder;

class AdminCompaniesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_companies')->delete();
        
        \DB::table('admin_companies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'ValueScale Technologies',
                'address' => 'A 10 , Sector 51, Noida',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 1,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 1,
                'city' => 'Noida',
                'state' => 'Uttar Pradesh',
                'country' => 'India',
                'email' => 'abhishek@valuescale.in',
                'phone' => '+919555129417',
                'website' => 'valuescale.in',
                'deleted_at' => '2021-03-29 18:07:03',
                'created_at' => '2020-09-15 16:10:52',
                'updated_at' => '2021-03-29 18:07:03',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Federal Inland Revenue Service',
                'address' => 'Wuse Zone 5',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'info@firs.com',
                'phone' => '+2348000000000',
                'website' => 'www.firs.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-23 18:21:22',
                'updated_at' => '2021-03-23 18:21:22',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Utako Microfinance Bank Ltd',
                'address' => 'Utako',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Utako District',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'info@utakomfb',
                'phone' => '08030000000',
                'website' => 'www.utakomfb.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-24 14:49:29',
                'updated_at' => '2021-03-24 14:49:29',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Nat. Urban Water sector reform Project',
                'address' => '10 Ajesa close',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'wuse 2',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'nuswrp@mail.com',
                'phone' => '088080890',
                'website' => 'nuwsrp.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-24 15:29:51',
                'updated_at' => '2021-03-24 15:29:51',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ify Best Computer & Stationeries',
                'address' => 'New Extension Wuse Model Market',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 1,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'info@ifybest.com',
                'phone' => '07064494870',
                'website' => 'www.ifybest.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-25 16:01:29',
                'updated_at' => '2021-03-25 16:32:49',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Maranatha Printing Press',
                'address' => 'Area 10 Garki',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 1,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'mpm@gmail.com',
                'phone' => '08066858508',
                'website' => 'www.mpm.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-25 16:15:59',
                'updated_at' => '2021-03-25 16:32:35',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Jimba Chambers',
                'address' => 'Abia House, CBD',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'jimbacambers@y',
                'phone' => '080808080',
                'website' => 'www.ajjazd.com',
                'deleted_at' => '2021-03-29 17:44:13',
                'created_at' => '2021-03-26 16:23:11',
                'updated_at' => '2021-03-29 17:44:13',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Student Registration',
                'address' => 'Quad Mall',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Mararaba',
                'state' => 'Nasarawa',
                'country' => 'Nigeria',
                'email' => 'info@imaginationtools.net',
                'phone' => '00000000000',
                'website' => 'www.imaginationtools.net',
                'deleted_at' => NULL,
                'created_at' => '2021-03-29 16:04:57',
                'updated_at' => '2021-03-29 16:06:04',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'National Directorate for Employement',
                'address' => 'Wuse Zone 1',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'nde@gmail.com',
                'phone' => '00000000001',
                'website' => 'www.nde.gov.ng',
                'deleted_at' => NULL,
                'created_at' => '2021-03-29 16:08:15',
                'updated_at' => '2021-03-29 16:08:30',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Ajjaz Properties',
                'address' => 'CBD',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'NGN',
                'email' => 'ajjazproperties@g.com',
                'phone' => '08080808080',
                'website' => 'www.ajjazproperties.com',
                'deleted_at' => NULL,
                'created_at' => '2021-03-29 17:58:09',
                'updated_at' => '2021-03-29 17:58:09',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Office & More Business Solutions Ltd',
                'address' => 'Silverbird Entertainment Centre',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 1,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Central Business District',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'sales@officenmore.net',
                'phone' => '07038167814',
                'website' => 'officenmore.net',
                'deleted_at' => NULL,
                'created_at' => '2021-04-08 16:00:21',
                'updated_at' => '2021-04-08 16:01:21',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'AEDC',
                'address' => 'Zone 4',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'admin@aedc.ng',
                'phone' => '0808080909',
                'website' => 'aedc.ng',
                'deleted_at' => NULL,
                'created_at' => '2021-04-14 17:03:40',
                'updated_at' => '2021-04-14 17:03:40',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'E.A ASHADE & CO',
                'address' => 'ZONE 5',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'ABUJA',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'tolaashade1@yahoo.com',
                'phone' => '08051634823',
                'website' => 'tolaashade',
                'deleted_at' => NULL,
                'created_at' => '2021-04-20 14:16:58',
                'updated_at' => '2021-04-20 14:16:58',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Omoneye Foods Ltd',
                'address' => 'Garki 2',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 1,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'omo.neye@gmail.com',
                'phone' => '00000000000',
                'website' => 'www.eye.com',
                'deleted_at' => NULL,
                'created_at' => '2021-04-20 19:44:05',
                'updated_at' => '2021-04-20 19:45:07',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Nigerian Export Promotion Council',
                'address' => 'Maitama',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'info@nepc.gov.ng',
                'phone' => '00000000000',
                'website' => 'www.nepc.gov.ng',
                'deleted_at' => NULL,
                'created_at' => '2021-04-26 15:11:37',
                'updated_at' => '2021-04-26 15:11:52',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'EBULK SMS',
                'address' => 'Abuja',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'Nigeria',
                'email' => 'ebulksms@bulksms.com',
                'phone' => '09090909',
                'website' => 'ebulksms.com',
                'deleted_at' => NULL,
                'created_at' => '2021-05-05 15:37:37',
                'updated_at' => '2021-05-05 15:38:27',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'FORETECH',
                'address' => 'WUSE ZONE 3',
                'is_tax_enabled' => 0,
                'is_customer' => 0,
                'is_supplier' => 0,
                'is_active' => 0,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'Federal Capital Territory',
                'country' => 'Nigeria',
                'email' => 'x@y.com',
                'phone' => '08033116467',
                'website' => 'www.y.com',
                'deleted_at' => NULL,
                'created_at' => '2021-05-06 21:14:45',
                'updated_at' => '2021-05-06 21:14:45',
            ),
            17 => 
            array (
                'id' => 18,
            'name' => 'GENERAL (DEFAULT) CUSTOMER',
                'address' => 'ABUJA',
                'is_tax_enabled' => 0,
                'is_customer' => 1,
                'is_supplier' => 0,
                'is_active' => 1,
                'is_cashbook_ac' => 0,
                'is_on_off' => 0,
                'is_pfa' => 0,
                'city' => 'Abuja',
                'state' => 'FCT',
                'country' => 'NIG',
                'email' => 'default@g.com',
                'phone' => '09090909',
                'website' => 'www.defaultgeneral.com',
                'deleted_at' => NULL,
                'created_at' => '2021-05-11 18:18:12',
                'updated_at' => '2021-05-11 18:18:12',
            ),
        ));
        
        
    }
}