<?php


namespace Modules\Treasury\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Treasury\Models\DefaultSetting;

class DefaultSettingRepository extends EloquentBaseRepository
{
    public $model = DefaultSetting::class;

    public function create($data)
    {
        $defaultSetting = DefaultSetting::where('id', 1)->first();

        if ($defaultSetting) {
            $data['id'] = 1;
            $defaultSetting = parent::update($data);
        } else {

            $defaultSetting = parent::create($data); // TODO: Change the autogenerated stub
        }
        return $defaultSetting;
    }

    public function getAll($params = [], $query = null)
    {
        $query = DefaultSetting::where('id', 1)
            ->with([
                'checking_officer',
                'financial_controller',
                'paying_officer',
                'account_head',
                'program_segment',
                'economic_segment',
                'functional_segment',
                'geo_code_segment',
                'admin_segment',
                'fund_segment',
                'sub_organisation',
                'children'
            ])->first();

        return $query;
    }

}
