<?php


namespace Modules\Treasury\Repositories;


use App\Constants\AppConstant;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Treasury\Models\PaymentApproval;

class PaymentApprovalRepository extends EloquentBaseRepository
{

    public $model = PaymentApproval::class;


    public function getAll($params = [], $query = null)
    {


        if (isset($params['inputs']['in_use'])) {
            $query = PaymentApproval::whereIn('status', [
                AppConstant::PAYMENT_APPROVAL_READY_FOR_PV,
                AppConstant::PAYMENT_APPROVAL_APPROVED_AND_READY
            ]);
        }
        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }

    public function create($data)
    {
        $data['data']['status'] = 'NEW';
        return parent::create($data);
    }

    public function update($data)
    {
        PaymentApproval::whereIn('id', json_decode($data['data']['payment_approval_ids'], true))->update([
            'status' => $data['data']['status']
        ]);
    }

}
