<?php


namespace Modules\Treasury\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Treasury\Models\ScheduleEconomic;

class ScheduleEconomicsRepository extends EloquentBaseRepository
{

    public $model = ScheduleEconomic::class;

    public function create($data)
    {
        foreach ($data['data']['schedule_economics'] as $key => $schedule_economic) {
            $data['data']['schedule_economics'][$key]['payee_voucher_id'] = (int)$data['data']['payee_voucher_id'];
        }



        dd($data['data']['schedule_economics']);
//        $data['data']  = $data['data']['schedule_economics'];
//        dd($data['data']['schedule_economics']);
       return ScheduleEconomic::insert($data['data']['schedule_economics']);
//        return parent::insert($data['data']['schedule_economics']);
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
