<?php


namespace Modules\Admin\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Admin\Models\AdminSegment;

class AdminSegmentRepository extends EloquentBaseRepository
{
    public $model = AdminSegment::class;

    public function create($data)
    {
        $arrayToMerge = ['combined_code' => $data['data']['individual_code']];
        if ($data["data"]["parent_id"]) {
            $parent = $this->find($data["data"]['parent_id'])->toArray();
            $arrayToMerge = [
                    'max_level' => $parent["max_level"] - 1,
                    'combined_code' => $parent["combined_code"].$data['data']['individual_code']
                ];
        }

        $data['data'] = array_merge($data['data'],$arrayToMerge);
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function getAll($params = [], $query = null)
    {
        $query = AdminSegment::with('sub_categories')->where('parent_id', null);
        return $query->get();
    }
}
