<?php


namespace Modules\Admin\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Admin\Models\Tax;

class TaxRepository extends EloquentBaseRepository
{

    public $model = Tax::class;

    public function update($data)
    {
        if (in_array((int)$data['id'], [1,2])){
            unset($data['data']['name']);
            unset($data['data']['is_active']);
        }
        return parent::update($data); // TODO: Change the autogenerated stub
    }

}
