<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\Department;

class DepartmentRepository extends EloquentBaseRepository
{
    public $model = Department::class;

    public function getAll($params = [], $query = null)
    {


        $query = Department::with('departments.departments.departments.departments')->where('parent_id', null);

//        $data = [];
//        $departments = Department::all();
//
//        /** @var Department $department */
//        foreach ($departments as $department)  {
//
//
//            if ($department->parent_id == null) {
//                $data['items'][] = $department;
//            }
////            if ($department->parent_id == ){
////                $data['items'][ ] = $department;
////            }
//        }
//
//        return $data;

        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}