<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\EmployeeBankDetail;

class EmployeeBankDetailsRepository extends EloquentBaseRepository
{
    public $model = EmployeeBankDetail::class;

    public function create($data)
    {
//        dd($data);
//        $data['data']['employee_id'] = $data['data']['employee_id'];
        return parent::create($data);
    }


    public function update($data)
    {
//        dd($data);
//        $data['data']['employee_id'] = $data['data']['id'];
        return parent::update($data);
    }

    public function getAll($params = [], $query = null)
    {
        $query = EmployeeBankDetail::where('employee_id', $params['inputs']['employee_id']);
        return parent::getAll($params, $query);
    }

    public function delete($data)
    {
        dd($data);
        $data['id'] = $data[''];
        return parent::delete($data); // TODO: Change the autogenerated stub
    }
}
