<?php


namespace Modules\Hr\Repositories;



use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\Employee;

class EmployeeRepository extends EloquentBaseRepository

{

    public $model = Employee::class;

    public function update($data)
    {
        dd($data);
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    public function customGet($params)
    {

        dd($params);

    }

    public function customPost1($data)
    {
        dd($data);
    }


}
