<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\GradeLevel;
use Modules\Hr\Models\GradeLevelStep;

class GLStepsRepository extends EloquentBaseRepository
{
    public $model = GradeLevelStep::class;

    public function create($data)
    {
        if (!isset($data['data']['name'])) {
            $gradeLevel = GradeLevel::find($data['data']['grade_level_id']);
            $currentGradeLevelCount = GradeLevelStep::where('grade_level_id', $data['data']['grade_level_id'])->count() +1;
            $data['data']['name'] = 'Level-'.str_pad($currentGradeLevelCount, 2, '0', STR_PAD_LEFT);
        }
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}