<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\JobPosition;

class JobPositionRepository extends EloquentBaseRepository
{

    public $model = JobPosition::class;

    public function getAll($params = [], $query = null)
    {
        $query = JobPosition::with('department','designation','salary_scale.grade_levels.grade_level_steps','skill', 'sub_categories')->where('parent_id', null)->get();
        return $query;
    }

    public function show($id, $params = null)
    {
        $data = parent::show($id, $params)->toArray();
        $data['departmentName'] = parent::show($id, $params)->toArray()['department']['name'] ?? null;
        return $data; // TODO: Change the autogenerated stub
    }
}