<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Exceptions\AppException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\EmployeeJobProfile;
use Modules\Hr\Models\JobPosition;

class JobPositionRepository extends EloquentBaseRepository
{

    public $model = JobPosition::class;

    public function getAll($params = [], $query = null)
    {
        $query = JobPosition::with('department','designation','salary_scale','grade_level','grade_level_step','skill', 'sub_categories')->where('parent_id', null)->get();
        return $query;
    }

    public function show($id, $params = null)
    {
        $data = parent::show($id, $params)->toArray();
        $data['departmentName'] = parent::show($id, $params)->toArray()['department']['name'] ?? null;
        return $data; // TODO: Change the autogenerated stub
    }

    public function delete($data)
    {
        $employeeJob = EmployeeJobProfile::where('job_position_id', $data['id'])->first();
        if (is_null($employeeJob)) {
            return parent::delete($data);
        }else {
            throw new AppException('Already in use');
        }
    }
}
