<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\LeaveScheduleReport;

class LeaveScheduleReportRepository extends EloquentBaseRepository
{
    public $model = LeaveScheduleReport::class;

    public function getAll($params = [], $query = null)
    {
        $query["inputs"]["created_at"] = null;
        $query = LeaveScheduleReport::query();
        if (isset($params["inputs"]["orderby"])) {
            $params["inputs"]["orderby"] = 'name';
            $params['inputs']['order'] = 'asc';
        }
        if (isset($params["inputs"]["search"])) {
            $query->where('personnel_file_number', 'like', '%' . $params['inputs']['search'] . '%')
            ->orWhere('FullName', 'like', '%' . $params['inputs']['search'] . '%')
            ->orWhere('EmpID', 'like', '%' . $params['inputs']['search'] . '%');
        }
        if (isset($params['inputs']['admin_segment_ids'])) {
            $query =    $query->whereHas('staff', function ($query) use ($params) {
                $query->whereHas('employee_job_profiles', function ($query) use ($params) {
                    $query->whereHas('department', function ($query) use ($params) {
                        $query->whereIn('id', json_decode($params['inputs']['admin_segment_ids'], true));
                    });
                });
            });
        }
        if (isset($params['inputs']['leave_type'])) {
            $query =    $query->whereHas('leave', function ($query) use ($params) {
                $query->where('id', 'like', '%' . $params['inputs']['leave_type'] . '%');
            });
        }
        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}
