<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\LeaveRequestReport;

class LeaveRequestReportRepository extends EloquentBaseRepository
{
    public $model = LeaveRequestReport::class;

    public function getAll($params = [], $query = null)
    {
        $query["inputs"]["created_at"] = null;
        $query = LeaveRequestReport::query();
        if (isset($params["inputs"]["orderby"])) {
            $params["inputs"]["orderby"] = 'name';
            $params['inputs']['order'] = 'asc';
        }
        if (isset($params["inputs"]["search"])) {
            $query->where('personnel_file_number', 'like', '%' . $params['inputs']['search'] . '%')
                ->orWhere('full_name', 'like', '%' . $params['inputs']['search'] . '%')
                ->orWhere('emp_id', 'like', '%' . $params['inputs']['search'] . '%');
        }
        if (isset($params['inputs']['admin_segment_ids'])) {
            $query =    $query->whereHas('staff', function ($query) use ($params) {
                $query->whereHas('employee_job_profiles', function ($query) use ($params) {
                    $query->whereHas('department', function ($query) use ($params) {
                        $query->whereIn('id', json_decode($params['inputs']['admin_segment_ids'], true));
                    });
                });
            });
        }
        if (isset($params['inputs']['from_date']) && isset($params['inputs']['to_date'])) {
            $fromDate = $params['inputs']['from_date'] . ' 00:00:00';
            $toDate = $params['inputs']['to_date'] . ' 23:59:59';
            $query->where('expected_start_date', '>=', $fromDate)
                ->where('expected_start_date', '<=', $toDate);
        }
        if (isset($params["inputs"]["status"])) {
            if ($params["inputs"]["status"] === 'hodpending') {
                $query->where('approved_hod', 'pending');
            } elseif ($params["inputs"]["status"] === 'hodapproved') {
                $query->where('approved_hod', 'approved');
            } elseif ($params["inputs"]["status"] === 'hrpending') {
                $query->where('approved_hr', 'pending');
            } elseif ($params["inputs"]["status"] === 'hrapproved') {
                $query->where('approved_hr', 'approved');
            }
        }
        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}
