<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Exceptions\AppException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\EmployeeMembership;
use Modules\Hr\Models\Membership;

class MembershipRepository extends EloquentBaseRepository
{

    public $model = Membership::class;

    public function delete($data)
    {
        $membership = EmployeeMembership::where('membership_id', $data['id'])->first();
        if (is_null($membership)) {
            return parent::delete($data);
        }else {
            throw new AppException('Already in use');
        }
    }

    public function getAll($params = [], $query = null)
    {

        if (isset($params["inputs"]["orderby"])) {
            $params["inputs"]["orderby"] = 'name';
            $params['inputs']['order'] = 'asc';
        }

        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}
