<?php


namespace Modules\Hr\Repositories;

use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\PublicHoliday;

class PublicHolidaysRepository extends EloquentBaseRepository
{
    public $model = PublicHoliday::class;

    public function create($data)
    {
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function getAll($params = [], $query = null)
    {

        if (isset($params["inputs"]["orderby"])) {
            $params["inputs"]["orderby"] = 'name';
            $params['inputs']['order'] = 'asc';
        }

        return parent::getAll($params, $query); // TODO: Change the autogenerated stub
    }
}
