<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Exceptions\AppException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\Region;
use Modules\Hr\Models\State;

class RegionRepository extends EloquentBaseRepository
{
    public $model = Region::class;

    public function getAll($params = [], $query = null)
    {

        $data = parent::getAll($params, $query); // TODO: Change the autogenerated stub
        $items = collect($data['items'])->sortBy('name')->sortBy('country.name')->all();
        $data['items'] = array_values($items);
        return $data;
    }

    public function delete($data)
    {
        $state = State::where('region_id', $data['id'])->first();
        if (is_null($state)) {
            return parent::delete($data);
        }else {
            throw new AppException('Already in use');
        }
    }
}
