<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Exceptions\AppException;
use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\Lga;
use Modules\Hr\Models\State;

class StateRepository extends EloquentBaseRepository
{

    public $model = State::class;


    public function getAll($params = [], $query = null)
    {
        $data = parent::getAll($params, $query); // TODO: Change the autogenerated stub
        $items = collect($data['items'])->sortBy('name')->sortBy('region.name')->sortBy('region.country.name')->all();
        $data['items'] = array_values($items);
        return $data;
    }

    public function delete($data)
    {
        $data = Lga::where('state_id', $data['id'])->first();
        if (is_null($data)) {
            return parent::delete($data);
        }else {
            throw new AppException('Already in use');
        }
    }
}
