<?php


namespace Modules\Hr\Repositories;


use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\Hr\Models\State;

class StateRepository extends EloquentBaseRepository
{

    public $model = State::class;


    public function getAll($params = [], $query = null)
    {
        $data = parent::getAll($params, $query); // TODO: Change the autogenerated stub
        $items = collect($data['items'])->sortBy('name')->sortBy('region.name')->sortBy('region.country.name')->all();
        $data['items'] = array_values($items);
        return $data;
    }
}
