<?php

namespace Modules\FixedAssets\Repositories;

use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\FixedAssets\Entities\FxaDeployment;
use Modules\FixedAssets\Entities\FxaDeprecationMethod;

class FxaDeploymentRepository extends EloquentBaseRepository
{
    public $model = FxaDeployment::class;

    public function create($data)
    {
        $data['data']['created_by_id'] = $data['data']['user_id'];
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
