<?php

namespace Modules\FixedAssets\Repositories;

use Luezoid\Laravelcore\Repositories\EloquentBaseRepository;
use Modules\FixedAssets\Entities\FxaDeployment;
use Modules\FixedAssets\Entities\FxaDepreciationMethod;
use Carbon\Carbon;

class FxaDeploymentRepository extends EloquentBaseRepository
{
    public $model = FxaDeployment::class;

    public function create($data)
    {
        $data['data']['created_by_id'] = $data['data']['user_id'];
        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function bulkCreate($data) {
        $dataToInsert = [];

        foreach ($data['data']['fixed_asset_ids'] as $fixedAssetId) {
            $dataToInsert[] = [
                'fxa_asset_id' => $fixedAssetId,
                'custodian_id' => $data['data']['custodian_id'],
                'value_date' => $data['data']['value_date'],
                'admin_segment_id' => $data['data']['admin_segment_id'],
                'location_id' => $data['data']['location_id'],
                'remark' => $data['data']['remark'] ?? null,
                'created_by_id' => $data['data']['user_id'],
                'created_at' => Carbon::now()->toDateString(),
                'updated_at' => Carbon::now()->toDateString()
            ];
        }

        if (count($dataToInsert)) {
            FxaDeployment::insert($dataToInsert);
        }

        return ['status' => 'success'];
    }
}
