<?php


namespace Modules\Hr\Http\Controllers;


use App\Http\Controllers\BaseController;
use Illuminate\Http\Request;
use Luezoid\Laravelcore\Jobs\BaseJob;
use Modules\Hr\Repositories\EmployeeBankDetailsRepository;

class EmployeeBankDetailController extends BaseController
{

    protected $repository = EmployeeBankDetailsRepository::class;
    protected $createJob = BaseJob::class;
    protected $updateJob = BaseJob::class;
    protected $deleteJob = BaseJob::class;
    protected $storeJobMethod = "create";
    protected $updateJobMethod = "update";

    protected $deleteJobMethod = "delete";


//    public function destroy(Request $request, $id)
//    {
//        dd($request->route('employeeId'));
//
//        return parent::destroy($request, $id); // TODO: Change the autogenerated stub
//    }
}
